language: node_js
node_js: 15

cache:
  directories:
    - node_modules

before_deploy:
  - "yarn generate"
  - "touch dist/.nojekyll"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master

